### ISSUE TITLE
Utils test and redux store compilation errors after upgrade to 0.6.11

### ISSUE THREAD

**Issue by AndriBoca** [pagopa/mui-italia#126]
https://github.com/pagopa/mui-italia/releases/tag/v0.6.11-RELEASE

Utils test and redux store compilation errors after upgrade to 0.6.11 on pn-frontend project

## ERROR in src/__test__/test-utils.tsx:11:31

<img width="1395" alt="Schermata 2022-04-20 alle 11 42 10" src="https://user-images.githubusercontent.com/100524063/164200238-40989e39-9180-4d47-9484-0631ce858310.png">

## ERROR in src/redux/store.ts:25:5
<img width="1395" alt="Schermata 2022-04-20 alle 11 44 12" src="https://user-images.githubusercontent.com/100524063/164200435-44dd4d55-c6e2-4263-aa6b-4222745a4cf0.png">

## ERROR in src/redux/store.ts:27:32
<img width="1415" alt="Schermata 2022-04-20 alle 11 45 32" src="https://user-images.githubusercontent.com/100524063/164200676-9d66fc20-6a7b-4952-8ef7-0d772c570ea7.png">
